name=Subo
version=1.0.0
author=AtumX <info@atumx.in>
maintainer=AtumX <info@atumx.in>
sentence=A library that allows for C Programming on Subo Board
paragraph=API to easily use Subo Board
category=Other
url=https://atumx.in/
architectures=*
includes=Subo.h
depends=Adafruit NeoPixel